language: java
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
jdk:
  - oraclejdk8
script:
  - mvn clean install
after_success:
  - mvn clean test jacoco:report coveralls:report
